### ISSUE TITLE
ئ character does not translate from inpage to unicode

### ISSUE THREAD

**Issue by naveednajam** [umer0586/unicode-inpage-converter#1]
Hi it's a great code and working almost correctly. Only Issue I found is somehow it is unable to translate ئ from inpage character 04£

**Comment by UmerCodez** [comment]
> Hi it's a great code and working almost correctly. Only Issue I found is somehow it is unable to translate ئ from inpage character 04£

The letter your referring is **Hamzah** in Urdu Script. **Hamzah** is written in both ways like ئ and ء but only ء could appear separately not ئ
In Urdu we write Dua as دعاء not دعائ,  its because script ئ is always used in combination with other letters like in the word کوئی where third character is ئ (Hamzah) , we don't write it as کوءی. 
So if someone write ئ as a single separate letter in Urdu text it would be a typing mistake and a given code will eventually maps ئ to ء

**Comment by naveednajam** [comment]
Yes, you are right and I understand this. But what I noticed is the letters **ئی** in inpage are written as **Hamzah** followed by **Yeh** which is **ءی** as these are two characters so your script translate them as it is rather than translating to **ئی** and in this case word **کوئی** from inpage translates into unicode as **کوءی**.  I noticed this because script only consider two bytes as a single character but this is similar to "آ" which is 3 bytes character. I am not sure if this case is only with my  system and inpage version or same everywhere.

**Comment by UmerCodez** [comment]
> Yes, you are right and I understand this. But what I noticed is the letters **ئی** in inpage are written as **Hamzah** followed by **Yeh** which is **ءی** as these are two characters so your script translate them as it is rather than translating to **ئی** and in this case word **کوئی** from inpage translates into unicode as **کوءی**. I noticed this because script only consider two bytes as a single character but this is similar to "آ" which is 3 bytes character. I am not sure if this case is only with my system and inpage version or same everywhere.

Okay i got your point، this is surely the **bug** in code. I'll **recheck** the code to fix this issue

*Thanks for pointing out problem*
